baseURL = 'https://cmdn.io/blog'
languageCode = 'en-us'
title = 'Cmd + N Blog'
theme = "paper"
publishDir = "../website/blog"

[params]
    # show header social icons
    twitter = 'cmdnio'     # twitter.com/YOUR_TWITTER_ID
    linkedin = 'cmdnio'       # github.com/YOUR_GITHUB_ID

    # show home page profile
    # avatar = 'GRAVATAR_EMAIL'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
    name = 'Cmd + N Blog'
    bio = 'We build MVPs for startups and greenfield projects for established companies. We can help you define the requirements necessary to test your business hypothesis and bring your idea into reality using the latest technological stack.'

    # misc
    disableHLJS = false              # disable requesting highlight.js
    monoDarkIcon = true             # show monochrome dark mode icon


[menu]
[[menu.main]]
  identifier = 'purpose'
  name = 'purpose'
  url = 'https://cmdn.io/#purpose'
  weight = -200

[[menu.main]]
  identifier = 'services'
  name = 'services'
  url = 'https://cmdn.io/#services'
  weight = -190

[[menu.main]]
  identifier = 'testimonials'
  name = 'testimonials'
  url = 'https://cmdn.io/#testimonials'
  weight = -170

[[menu.main]]
  identifier = 'team'
  name = 'team'
  url = 'https://cmdn.io/#team'
  weight = -160

[[menu.main]]
  identifier = 'team'
  name = 'team'
  url = 'https://cmdn.io/#team'
  weight = -150

[[menu.main]]
  identifier = 'blog'
  name = 'blog'
  url = 'https://cmdn.io/blog'
  weight = -140

[[menu.main]]
  identifier = 'contact'
  name = 'contact'
  url = 'https://cmdn.io/#contact'
  weight = -130
